### ISSUE TITLE
'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

### ISSUE THREAD

**Issue by Arham-Aalam** [OzymandiasTheGreat/winnotify#1]
Getting this:
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

code:
```
notify.notify('This notification body', 'Title', 'C:\Users\username\Downloads\python.ico', False, 5, notify.dwInfoFlags.NIIF_USER | notify.dwInfoFlags.NIIF_LARGE_ICON)
```

**Comment by OzymandiasTheGreat** [comment]
Well, that right there, `SyntaxError` indicates that's it's not an error with this library but your code. You have invalid Unicode characters in your source. I don't know what, I know where, but I can't really help you with this.
